### ISSUE TITLE
Line 168 of index.php

### ISSUE THREAD

**Issue by aledbrown** [halkyon/silverstripe-reqchecker#1]
Cool checker. Worked a treat. Thank you for making it available.

But I think the code should be ini_get('eaccelerator.enable') not ini.get on line 168.

That worked for me.

Full line 168:
elseif($this->assertPhpExtensionLoaded('eaccelerator') && ini_get('eaccelerator.enable')) return trim('eAccelerator ' . $this->getPhpExtensionVersion('eaccelerator'));

**Comment by halkyon** [comment]
Thanks for that, super late response I know, but fixed in cc00c10bed42a02bd8dc11ec7d453e27b5cc8074 for what it's worth 😄
